# Generated by Django 3.2 on 2021-05-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0002_auto_20210527_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bestarticle', to='clientside.article'),
        ),
    ]
