# Generated by Django 3.2 on 2021-05-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0003_alter_bestarticle_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='childcategory',
        ),
        migrations.AddField(
            model_name='childcategory',
            name='Article',
            field=models.ForeignKey(default=12, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleChildCategory', to='clientside.article'),
            preserve_default=False,
        ),
    ]
