# Generated by Django 3.2 on 2021-05-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0004_auto_20210529_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcategory',
            name='Article',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleChildCategory', to='clientside.article'),
        ),
    ]
