# Generated by Django 3.2 on 2021-05-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0005_alter_childcategory_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
