# Generated by Django 3.2 on 2021-05-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0008_alter_article_childcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='childcategory',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleChildCategory', to='clientside.childcategory'),
        ),
    ]
