# Generated by Django 3.2 on 2021-05-30 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0009_alter_article_childcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='childcategory',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleChildCategory', to='clientside.childcategory'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('childcategory', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='SearchChildCategory', to='clientside.childcategory')),
            ],
        ),
    ]
