# Generated by Django 3.2 on 2021-05-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0010_auto_20210530_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopRecherch',
        ),
    ]
