# Generated by Django 3.2 on 2021-05-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0011_delete_toprecherch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchHistory',
            new_name='CategoryHistory',
        ),
    ]
