# Generated by Django 3.2 on 2021-05-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0012_rename_searchhistory_categoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhistory',
            name='childcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SearchChildCategory', to='clientside.childcategory'),
        ),
    ]
