# Generated by Django 3.2 on 2021-05-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0013_alter_categoryhistory_childcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse1',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse2',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='codepostal',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoryhistory',
            name='childcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildCategoryHistory', to='clientside.childcategory'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tele',
            field=models.TextField(max_length=14, null=True),
        ),
    ]
