# Generated by Django 3.2 on 2021-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0014_auto_20210530_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse2',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilite',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='codepostal',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='tele',
            field=models.TextField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
