# Generated by Django 3.2 on 2021-05-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0015_auto_20210530_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='customSize',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='finition',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='fontColor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='orientation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='paperColor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='paperType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='side',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
