# Generated by Django 3.2.3 on 2021-06-04 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientside', '0017_auto_20210530_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Article image'},
        ),
        migrations.AlterModelOptions(
            name='bestarticle',
            options={'verbose_name': 'Top article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='categoryhistory',
            options={'verbose_name': 'Categories historique'},
        ),
        migrations.AlterModelOptions(
            name='childcategory',
            options={'verbose_name': 'Sous categorie'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='finition',
            options={'verbose_name': 'Finition'},
        ),
        migrations.AlterModelOptions(
            name='fontcolor',
            options={'verbose_name': 'Font coleur'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='orientation',
            options={'verbose_name': 'Orientation'},
        ),
        migrations.AlterModelOptions(
            name='papercolor',
            options={'verbose_name': 'Papier coleur'},
        ),
        migrations.AlterModelOptions(
            name='papertype',
            options={'verbose_name': 'Papier type'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Recherche'},
        ),
        migrations.AlterModelOptions(
            name='size1',
            options={'verbose_name': 'Size'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Specification'},
        ),
        migrations.AddField(
            model_name='specification',
            name='customQuantite',
            field=models.BooleanField(null=True, verbose_name='client choisi Quantite'),
        ),
        migrations.AlterField(
            model_name='article',
            name='childcategory',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleChildCategory', to='clientside.childcategory', verbose_name='Sous categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='complementes',
            field=models.TextField(null=True, verbose_name='Produits complémentaires'),
        ),
        migrations.AlterField(
            model_name='article',
            name='conseil',
            field=models.TextField(null=True, verbose_name='Conseils Techniques'),
        ),
        migrations.AlterField(
            model_name='article',
            name='info',
            field=models.TextField(null=True, verbose_name='Infos produit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='options',
            field=models.TextField(null=True, verbose_name='Options - Finitions'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleimages', to='clientside.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='name',
            field=models.FileField(upload_to='static/product_images', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='bestarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bestarticle', to='clientside.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoryhistory',
            name='childcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildCategoryHistory', to='clientside.childcategory', verbose_name='Sous categorie'),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildCategory', to='clientside.category', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse1',
            field=models.TextField(default='', max_length=100, verbose_name='Adresse 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse2',
            field=models.TextField(default='', max_length=150, verbose_name='Adresse 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.TextField(default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilite',
            field=models.CharField(default='', max_length=10, verbose_name='Civilite'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codepostal',
            field=models.TextField(default='', max_length=150, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.TextField(default='', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tele',
            field=models.TextField(default='', max_length=14, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ClientUser', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='finition',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='finition',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='fontcolor',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='fontcolor',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='orientation',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='orientation',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='papercolor',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='papercolor',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='side',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='side',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='size1',
            name='height',
            field=models.FloatField(null=True, verbose_name='Largeur'),
        ),
        migrations.AlterField(
            model_name='size1',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='size1',
            name='width',
            field=models.FloatField(null=True, verbose_name='Longeur'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecificationArticle', to='clientside.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='customSize',
            field=models.BooleanField(null=True, verbose_name='client choisi longeur et largeur'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='finition',
            field=models.ManyToManyField(related_name='FinitionSpecification', to='clientside.Finition', verbose_name='Finition'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='fontColor',
            field=models.ManyToManyField(related_name='FontColorSpecification', to='clientside.FontColor', verbose_name='font coleur'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='orientation',
            field=models.ManyToManyField(related_name='OrientationSpecification', to='clientside.Orientation', verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='paperColor',
            field=models.ManyToManyField(related_name='PaperColorSpecification', to='clientside.PaperColor', verbose_name='Papier coleur'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='paperType',
            field=models.ManyToManyField(related_name='PaperSpecification', to='clientside.PaperType', verbose_name='Papier type'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='side',
            field=models.ManyToManyField(related_name='SideSpecification', to='clientside.Side', verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='size',
            field=models.ManyToManyField(related_name='SizeSpecification', to='clientside.Size1', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='specification',
            name='Quantity',
            field=models.ManyToManyField(related_name='QuantitySpecification', to='clientside.Quantity', verbose_name='Quantite'),
        ),
    ]
