# Generated by Django 3.2.3 on 2021-06-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0021_alter_specification_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SpecificationArticle', to='clientside.article', verbose_name='Article'),
        ),
    ]
