# Generated by Django 3.2.3 on 2021-06-04 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0023_auto_20210604_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='specification',
            name='formattype',
            field=models.ManyToManyField(blank=True, related_name='FormaTypeSpecification', to='clientside.FormatType', verbose_name='FromaTypeSpecification'),
        ),
    ]
