# Generated by Django 3.2.3 on 2021-06-04 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientside', '0024_auto_20210604_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='fontcolor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orientation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='papercolor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='side',
            name='price',
        ),
        migrations.RemoveField(
            model_name='size1',
            name='price',
        ),
        migrations.AddField(
            model_name='specification',
            name='customDesign',
            field=models.BooleanField(blank=True, null=True, verbose_name='client Charger un design'),
        ),
        migrations.CreateModel(
            name='Pane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleDesign', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('Quantity', models.ManyToManyField(blank=True, related_name='QuantityPane', to='clientside.Quantity', verbose_name='Quantite')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticlePane', to=settings.AUTH_USER_MODEL)),
                ('finition', models.ManyToManyField(blank=True, related_name='FinitionPane', to='clientside.Finition', verbose_name='Finition')),
                ('fontColor', models.ManyToManyField(blank=True, related_name='FontColorPane', to='clientside.FontColor', verbose_name='Font coleur')),
                ('formattype', models.ManyToManyField(blank=True, related_name='FormaTypePane', to='clientside.FormatType', verbose_name='Forma type')),
                ('orientation', models.ManyToManyField(blank=True, related_name='OrientationPane', to='clientside.Orientation', verbose_name='Orientation')),
                ('paperColor', models.ManyToManyField(blank=True, related_name='PaperColorPane', to='clientside.PaperColor', verbose_name='Papier coleur')),
                ('paperType', models.ManyToManyField(blank=True, related_name='PaperPane', to='clientside.PaperType', verbose_name='Papier type')),
                ('side', models.ManyToManyField(blank=True, related_name='SidePane', to='clientside.Side', verbose_name='direction')),
                ('size', models.ManyToManyField(blank=True, related_name='SizePane', to='clientside.Size1', verbose_name='Size')),
            ],
        ),
    ]
