# Generated by Django 3.2.3 on 2021-06-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0025_auto_20210604_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Specification Pdf'),
        ),
    ]
