# Generated by Django 3.2.3 on 2021-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0028_auto_20210605_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pane',
            name='Quantity',
            field=models.ManyToManyField(blank=True, null=True, related_name='QuantityPane', to='clientside.Quantity', verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='finition',
            field=models.ManyToManyField(blank=True, null=True, related_name='FinitionPane', to='clientside.Finition', verbose_name='Finition'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='fontColor',
            field=models.ManyToManyField(blank=True, null=True, related_name='FontColorPane', to='clientside.FontColor', verbose_name='Font coleur'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='formattype',
            field=models.ManyToManyField(blank=True, null=True, related_name='FormaTypePane', to='clientside.FormatType', verbose_name='Forma type'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='orientation',
            field=models.ManyToManyField(blank=True, null=True, related_name='OrientationPane', to='clientside.Orientation', verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='paperColor',
            field=models.ManyToManyField(blank=True, null=True, related_name='PaperColorPane', to='clientside.PaperColor', verbose_name='Papier coleur'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='paperType',
            field=models.ManyToManyField(blank=True, null=True, related_name='PaperPane', to='clientside.PaperType', verbose_name='Papier type'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='side',
            field=models.ManyToManyField(blank=True, null=True, related_name='SidePane', to='clientside.Side', verbose_name='direction'),
        ),
    ]
