# Generated by Django 3.2.3 on 2021-06-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0029_auto_20210605_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='pane',
            name='delevery',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DeleveryPane', to='clientside.delivery'),
            preserve_default=False,
        ),
    ]
