# Generated by Django 3.2.3 on 2021-06-05 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientside', '0030_pane_delevery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pane',
            name='delevery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeleveryPane', to='clientside.delivery'),
        ),
        migrations.AlterField(
            model_name='pane',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPane', to=settings.AUTH_USER_MODEL),
        ),
    ]
