# Generated by Django 3.2.3 on 2021-06-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0032_auto_20210605_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pane',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='pane',
            name='Quantity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuantityPane', to='clientside.quantity', verbose_name='Quantite'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='finition',
        ),
        migrations.AddField(
            model_name='pane',
            name='finition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FinitionPane', to='clientside.finition', verbose_name='Finition'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='fontColor',
        ),
        migrations.AddField(
            model_name='pane',
            name='fontColor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FontColorPane', to='clientside.fontcolor', verbose_name='Font coleur'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='formattype',
        ),
        migrations.AddField(
            model_name='pane',
            name='formattype',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FormaTypePane', to='clientside.formattype', verbose_name='Forma type'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='orientation',
        ),
        migrations.AddField(
            model_name='pane',
            name='orientation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrientationPane', to='clientside.orientation', verbose_name='Orientation'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='paperColor',
        ),
        migrations.AddField(
            model_name='pane',
            name='paperColor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaperColorPane', to='clientside.papercolor', verbose_name='Papier coleur'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='paperType',
        ),
        migrations.AddField(
            model_name='pane',
            name='paperType',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaperPane', to='clientside.papertype', verbose_name='Papier type'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='side',
        ),
        migrations.AddField(
            model_name='pane',
            name='side',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SidePane', to='clientside.side', verbose_name='direction'),
        ),
        migrations.RemoveField(
            model_name='pane',
            name='size',
        ),
        migrations.AddField(
            model_name='pane',
            name='size',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SizePane', to='clientside.size1', verbose_name='Size'),
            preserve_default=False,
        ),
    ]
