# Generated by Django 3.2.3 on 2021-06-05 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0033_auto_20210605_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('creatd_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='pane',
            name='size',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SizePane', to='clientside.size1', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='pane',
            name='FileControle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FileControlePane', to='clientside.filecontrole'),
            preserve_default=False,
        ),
    ]
