# Generated by Django 3.2.3 on 2021-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0035_auto_20210607_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pane',
            name='ArticleDesign',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
