# Generated by Django 3.2.3 on 2021-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0036_alter_pane_articledesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pane',
            name='ArticleDesign',
            field=models.FileField(blank=True, null=True, upload_to='static/pane_images', verbose_name='Nom'),
        ),
    ]
