# Generated by Django 3.2.3 on 2021-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0037_alter_pane_articledesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='pane',
            name='CostumQuantity',
            field=models.IntegerField(null=True),
        ),
    ]
