# Generated by Django 3.2.3 on 2021-06-23 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0038_pane_costumquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('Pane', models.ManyToManyField(related_name='panes', to='clientside.Pane')),
            ],
        ),
    ]
