# Generated by Django 3.2.3 on 2021-06-23 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientside', '0039_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='User',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
