# Generated by Django 3.2.3 on 2021-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0041_auto_20210623_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
