# Generated by Django 3.2.3 on 2021-06-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0042_auto_20210624_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delevery',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Deleverycommande', to='clientside.delivery'),
            preserve_default=False,
        ),
    ]
