# Generated by Django 3.2.3 on 2021-06-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0044_alter_pane_articledesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
