# Generated by Django 3.2.3 on 2021-06-30 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0045_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Pane',
        ),
        migrations.AddField(
            model_name='commande',
            name='Article',
            field=models.ManyToManyField(related_name='panes', to='clientside.Article'),
        ),
        migrations.AlterField(
            model_name='message',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(4, 'Minimun est 4 champs')]),
        ),
    ]
