# Generated by Django 3.2.3 on 2021-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0047_auto_20210630_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Pane',
        ),
        migrations.AddField(
            model_name='commande',
            name='LastPane',
            field=models.ManyToManyField(related_name='panes', to='clientside.LastPane'),
        ),
    ]
