# Generated by Django 3.2.3 on 2021-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0048_auto_20210630_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En Livraison', 'En Livraison'), ('Livrée', 'Livrée')], default='En attente', max_length=50),
        ),
    ]
