# Generated by Django 3.2.3 on 2021-07-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0049_commande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='LastPane',
        ),
        migrations.AddField(
            model_name='commande',
            name='LastPane',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='panes', to='clientside.lastpane'),
            preserve_default=False,
        ),
    ]
