# Generated by Django 3.2.3 on 2021-07-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0050_auto_20210708_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='LastPane',
        ),
        migrations.AddField(
            model_name='lastpane',
            name='commande',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='CommandeLastPane', to='clientside.commande'),
            preserve_default=False,
        ),
    ]
