# Generated by Django 3.2.3 on 2021-07-09 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0051_auto_20210708_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpane',
            name='commande',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='CommandeLastPane', to='clientside.commande'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='Quantity',
            field=models.ManyToManyField(blank=True, null=True, related_name='QuantitySpecification', to='clientside.Quantity', verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='finition',
            field=models.ManyToManyField(blank=True, null=True, related_name='FinitionSpecification', to='clientside.Finition', verbose_name='Finition'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='fontColor',
            field=models.ManyToManyField(blank=True, null=True, related_name='FontColorSpecification', to='clientside.FontColor', verbose_name='Font coleur'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='formattype',
            field=models.ManyToManyField(blank=True, null=True, related_name='FormaTypeSpecification', to='clientside.FormatType', verbose_name='FromaTypeSpecification'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='orientation',
            field=models.ManyToManyField(blank=True, null=True, related_name='OrientationSpecification', to='clientside.Orientation', verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='paperColor',
            field=models.ManyToManyField(blank=True, null=True, related_name='PaperColorSpecification', to='clientside.PaperColor', verbose_name='Papier coleur'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='paperType',
            field=models.ManyToManyField(blank=True, null=True, related_name='PaperSpecification', to='clientside.PaperType', verbose_name='Papier type'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='side',
            field=models.ManyToManyField(blank=True, null=True, related_name='SideSpecification', to='clientside.Side', verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='SizeSpecification', to='clientside.Size1', verbose_name='Size'),
        ),
    ]
